apiVersion: apps/v1
kind: Deployment
metadata:
  name: huey-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huey-worker
  template:
    metadata:
      labels:
        app: huey-worker
    spec:
      containers:
      - name: huey-worker
        image: slicedb/huey-worker:v1.0
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: HUEY_REDIS
          value: "redis-service"
        - name: HUEY_REDIS_PORT
          value: "6379"
        - name: KV_HOST
          value: "slice-db-svc"  
        - name: KV_PORT
          value: "6380"
---
apiVersion: v1
kind: Service
metadata:
  name: huey-worker-service
spec:
  selector:
    app: huey-worker
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
